//QUESTION 2_1
//MVI B,20H // STORE '20H' INTO REGISTER B
//MOV A,B // MOVE DATA OF REGISTER B TO REGISTER A
//XRI FFH  // ITS DONE 1'S COMPLIMENT AND STORE RESULT IN //ACCUMULATOR
//ADI 01H // ITS DONE 2'S COMPLIMENT BY ADDING 1 INTO ACCUMULATOR'S DATA
//HLT

//QUESTION 2_2
//LXI H,3020H//LOAD THE 16 BIT DATA INTO REGISTER PAIR HL
//MOV A,L //MOVE LOWER NIBBLE TO ACCUMULATOR
//CMA  // ITS DONE 1'S COMPLIMENT OF ACCUMULATOR CONTENT
//MOV E,A//MOVE 1'S COMPLIMENT OF L INTO REGISTER E
//MOV A,H//MOVE CONTENT OF REGISTER H INTO ACCUMULATOR TO DO 1'S COMPLIMENT OF REMAINING PART
//CMA //ITS DONE 1'S COMPLIMENT OF ACCUMULATOR CONTENT
//MOV D,A//MOVE 1'S COMPLIMENT OF H INTO REGISTER D
//INX D // DONE INCRIMENT OF REGISTER PAIR DE, SO 2'S COMPLIMENT WILL DONE
//HLT // HOLD AND WAIT

//QUESTION 2_3
//MVI A, 3CH//STORE '3CH' INTO ACCUMULATOR 
//MOV B,A//MOVE CONTENT OF A TO REGISTER B
//ANI F0H//PERFORM 'AND' OPERATION WITH CONTENT OF ACCUMULATOR ITS DONE LOWER NIBBLE MASK
//OUT 30H//STORE THE VALUE OF ACCUMULATOR TO MEMORY LOCATION '30H'
//MOV A,B//MOVE CONTENT OF B TO ACCUMULATOR
//ANI AAH//PERFORM 'AND' OPERATION WITH CONTENT OF ACCUMULATOR ITS DONE ALL EVEN BIT MASKED
//OUT 31H//STORE THE VALUE OF ACCUMULATOR TO MEMORY LOCATION '31H'
//MOV A,B//MOVE CONTENT OF B TO ACCUMULATOR
//ANI 00H//PERFORM 'AND' OPERATION WITH CONTENT OF ACCUMULATOR ITS DONE ALL BITS MASKED
//OUT 32H//STORE THE VALUE OF ACCUMULATOR TO MEMORY LOCATION '32H'
//HLT//HOLD AND WAIT

//QUESTION 2_4
//MVI A,50H//STORE '50H' INTO ACCUMULATOR 
//MOV B,A//MOVE CONTENT OF A TO REGISTER B
//XRI A0H//PERFORM 'XOR' OPERATION WITH CONTENT OF ACCUMULATOR ITS DONE UPPER NIBBLE UNMASK
//OUT 10H//STORE THE VALUE OF ACCUMULATOR TO MEMORY LOCATION '10H'
//MOV A,B//MOVE CONTENT OF B TO ACCUMULATOR
//XRI FAH//PERFORM 'XOR' OPERATION WITH CONTENT OF ACCUMULATOR ITS DONE ALL ODD BITS UNMASK
//OUT 11H//STORE THE VALUE OF ACCUMULATOR TO MEMORY LOCATION '11H'
//MOV A,B//MOVE CONTENT OF B TO ACCUMULATOR
//XRI AFH//PERFORM 'XOR' OPERATION WITH CONTENT OF ACCUMULATOR ITS DONE ALL BITS UNMASK
//OUT 12H//STORE THE VALUE OF ACCUMULATOR TO MEMORY LOCATION '12H'
//HLT//HOLD AND WAIT

//QUESTION 2_5
//MVI A,20H//STORE '20H' INTO ACCUMULATOR
//OUT 03H//STORE CONTENT OF ACCUMULATOR INTO MEMORY LOCATION '03H'
//IN 03H//TAKE INPUT VALUE FROM LOCATION '03H' AND STORE INTO ACCUMULATOR
//XRI 0FH//PERFORM 'XOR' OPERATION WITH ACCUMULATOR ITS DONE "1's" COMPLEMENT OF LOWER NIBBLE 
//OUT 04H//STORE THE RESULT IN MEMORY LOCATION '04H' WHICH IS EXIST IN ACCUMULATOR
//HLT//HOLD AND WAIT

//QUESTION 2_6
//MVI A,D4H//STORE 'D4H' INTO ACCUMULATOR
//OUT 30H//STORE CONTENT OF ACCUMULATOR INTO MEMORY LOCATION '30H'
//IN 30H//TAKE INPUT VALUE FROM LOCATION '30H' AND STORE INTO ACCUMULATOR
//XRI F0H//PERFORM 'XOR' OPERATION WITH ACCUMULATOR ITS DONE "1's" COMPLEMENT OF UPPER NIBBLE 
//OUT 31H//STORE THE RESULT IN MEMORY LOCATION '31H' WHICH IS EXIST IN ACCUMULATOR
//HLT//HOLD AND WAIT

//QUESTION 2_7
MVI A,B2H // SET A VALUE TO PERFORM OPERATION
OUT 10H // Store Result in memory location '10H'
RLC //Rotate Accumulator Left
OUT 11H // Store Result in memory location '11H'
RAL //Rotate Accumulator Left Through Carry
OUT 12H// Store Result in memory location '12H'
MVI A,A2H // SET NEW VALUE TO PERFORM ANOTHER OPERATION
OUT 20H // Store Result in memory location '20H'
RRC // Rotate Accumulator Right
OUT 21H // Store Result in memory location '21H'
RAR //Rotate Accumulator Right Through Carry
OUT 22H // Store Result in memory location '22H'
MVI A,4BH//TAKE VALUE TO PERFORM CMP & CPI OPERATION
OUT 30H // INITIAL DATA
MVI B,4BH
CMP B //COMPARE THE DATA 'B' WITH REGISTER 'A'  FOR LESS THAN| EQUAL TO | GREATER THAN,RESULT REFLECT IN FLAG REGISTER
CPI 8AH //COMPARE THE 8-BIT DATA  WITH REGISTER 'A'  FOR LESS THAN| EQUAL TO | GREATER THAN,RESULT REFLECT IN FLAG REGISTER
HLT









