	   MVI A,A2H	// MOVE A2H IN ACCUMULATOR
	   OUT 15H	// STORE ACCUMULATOR DATA IN MEMORY ADDRESS 15H
	   MVI A,08H	// MOVE 08H IN ACCUMULATOR
	   OUT 16	// STORE ACCUMULATOR DATA IN MEMORY ADDRESS 15H
	   IN 16H	// FETCH DATA FROM ADDRESS 16H
	   MOV C,A	// MOVE ACCUMULATOR DATA INTO REGISTER C FOR COUNTER
	   IN 15H	// FETCH DATA FROM ADDRESS 15H
	   MOV D,A	// MOVE ACCUMULATOR DATA INTO REGISTER D & ITS ACT AS A MULTIPLICAND
	   MVI A,00H	// ACCUMULATOR HOLD CURRENT SUM
	   MVI E,00H	// ITS HOLD CARRY SUM

AGAIN:	   ADD D	// AGAIN IS LABEL WHICH IS ACT AS A LOOP AND ADD D ISTRUCTION IN ADD DATA D INTO REGISTER A
	   JNC CARRY	// IT WILL JUMP IF THEIR WILL BE NO CARRY
	   INR E	// INCREMENT HIGHER BYTE

CARRY:	   DCR C	// DECREMENT COUNTER
	   JNZ AGAIN	// IT WILL JUMP ON AGAIN WHEN ZERO FLAG IS RESET
	   STA 3000H// STORE LOWERBYTE RESULT AT 3000H
	   MOV A,E	// MOVE HIGHER BYTE IN ACCUMULATOR
	   STA 3001H// STORE HIGHER BYTE AT 3001H
	   HLT	// HOLD
