# ORG 1000H
# DB 05H,12H,23H,34H,45H,56H,67H,78H,89H,9AH
# ORG 1100H
	   LXI H,1000H	// LOAD FIRST DATA'S ADDRESS INTO HL PAIR
	   MVI C,0AH	// COUTER
	   MVI D,00H	// REGISTER FOR HIGHER BYTE
	   MVI E,00H	// REGISTER FOR LOWER BYTE

NEXT:	   MOV A,M	// FETCH DATA FROM MEMORY ADDRESS AND STORE IT TO ACCUMULATOR
	   ADD E	// ADD LSB
	   MOV E,A	// STORE LSB IN REGISTER E
	   JNC LABEL	// JUMP ON LABEL IF CARRY FLAG IS SET TO 0
	   INR D	// INCREMENT MSB

LABEL:	   INX H	// INCREMENT HL PAIR TO GET NEXT DATA
	   DCR C	// DECREMENT COUNTER
	   JNZ NEXT	// JUMP ON NEXT IF ZERO FLAG IS SET TO 0
	   LXI H,2000H	// LOAD 2000H ADDRESS IN HL PAIR
	   MOV M,E	// STORE LSB IN MEMORY LOCATION WHICH IS DEFINED IN HL PAIR
	   INX H	// INCREMENT HL PAIR
	   MOV M,D	// STORE MSB IN MEMORY LOCATION WHICH IS DEFINED IN HL PAIR
	   HLT	// stop
