MVI H,05H	// STORE 05H IN REGISTER H
MVI L,0AH	// STORE 0AH IN REGISTER L

// Program to subtract H from L using 2's complement
//MOV A,H	// MOVE REGITER H DATA INTO ACCUMULATOR
//CMA	// PERFORM 1'S COMPLIMENT OF ACCUMULATOR
//INR A	// ADD 1 IN ACCUMULATOR DATA FOR 2'S COMPLIMENT
//ADD L	// ADD L INTO H THEN SUBTRACTION PERFORM
//MOV L,A	// STORE RESULT IN REGISTER L
//HLT	// STOP

// Program to subtract H from L using 1's complement
MOV A,H	// MOVE REGITER H DATA INTO ACCUMULATOR
CMA	// PERFORM 1'S COMPLIMENT OF ACCUMULATOR
ADD L	// PERFORM ADD OPERATION WITH REGISTER A AND L
INR A	// ADD 1 IN ACCUMULATOR'S DATA
MOV L,A	// STORE RESULT IN REGITER L
HLT	// STOP
