# ORG 1020H
# DB 45H,C4H,FFH,72H,A0H,E3H,99H,15H,85H,F0H
# ORG 0000H
	   MVI A,09
	   LXI D,101F
	   STAX D
	   LXI H,101F
	   MOV C,M
// ////////////////////////////////////////////////////////////////
	   LXI H,1020 ;SET HL PAIR FOR START FROM FIRST DATA
	   MOV A,M ;LOAD FIRST DATA ASSUME ITS TEMPORARY MAX

LOOP:	   INX H ;INCREMENT HL PAIR FOR STARTING COMARISON FROM SECOND DATA
	   CMP M ;COMPARE MEMORY DATA WITH ACCUMULATOR
	   JNC SKIP ;JUMP ON SKIP IF MEMORY DATA IS NOT GREATER THAN A
	   MOV B,M ;IF DATA IS GREATER THEN MOVE IT INTO REG B ITS CARRY OUR MAXIMUM NUMBER
	   MOV A,M ;UPDATE TEMPORARY MAX
	   SKIP:DCR C ;DECREMENT COUNTER
	   JNZ LOOP ;JUMP ON LOOP
	   OUT 10 ;STORE OUR MAX DATA IN PORT 10H

HOLD:	   HLT
